# -*- coding: utf-8 -*-
"""Study.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IKNBmyYJGJYq-saN2gOTJe4hPJzYjB3i
"""

import numpy as np
import random as rd
import matplotlib.pyplot as plt

def studentReg(ages_train,net_worths_train):
  from sklearn.linear_model import LinearRegression
  reg=LinearRegression()
  reg.fit(ages_train,net_worths_train)
  return reg

rd.seed(42)
np.random.seed(42)

ages=[]

for i in range(100):
  ages.append(rd.randint(20,65))

net_worths=[i*6.25+np.random.normal(scale=40.0)for i in ages]

ages=np.reshape(np.array(ages),(len(ages),1))
net_worths=np.reshape(np.array(net_worths),(len(net_worths),1))

from sklearn.model_selection import train_test_split
ages_train,ages_test,net_worths_train,net_worths_test=train_test_split(ages,net_worths)

reg=studentReg(ages_train,net_worths_train)

print("Coefficient: ",reg.coef_)
print("Slope: ",reg.intercept_)

print("Testing data: ",reg.score(ages_test,net_worths_test))
print("Training data: ",reg.score(ages_train,net_worths_train))

plt.plot(ages_test,reg.predict(ages_test))
plt.xlabel("Ages")
plt.ylabel("Net Worths")
plt.show()

